global using Redzen;
global using Redzen.Collections;
global using Redzen.Random;
global using Redzen.Structures;
global using SharpNeat.Evaluation;
global using SharpNeat.EvolutionAlgorithm;
global using SharpNeat.Graphs;
global using SharpNeat.Neat.Genome;
global using SharpNeat.Neat.Speciation;
