on:
 push:
    branches:
      - main
      - 'releases/**'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
#    - name: Verify commit exists in origin/main
#      run: |
#        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
#        git branch --remote --contains | grep origin/main        
    - name: Set VERSION variable from tag
      run: |
        echo "VERSION=$(date +%y.%-m.%-d%M)" >> $GITHUB_ENV        
    - name: Build
      run: dotnet build src/SharpNeat/SharpNeat.csproj --configuration Release /p:Version=${VERSION}    
    - name: Pack
      run: dotnet pack src/SharpNeat/SharpNeat.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push SharpNeat.${VERSION}.nupkg --source https://nuget.feeluptechnologies.com --api-key ${FEELUP_NUGET_API_KEY}
      env:
        FEELUP_NUGET_API_KEY: ${{ secrets.FEELUP_NUGET_API_KEY }}